export const kliniks = [
  {
    id: "0",
    name: "AMEOS Hospital Alfeld",
    address: "Landrat-Beushausen-Straße 26, 31061 Alfeld (Leine)",
    stadt: "Alfeld (Leine)",
    Google: 2.4,
    Klinikum: 1.7,
    rating_klinify: 1,
    image:
      "https://www.deutsches-krankenhaus-verzeichnis.de/app/file/image/show/d204dee453d62f16_cf0c2632-24ac-4b3f-8448-c29f6e68906a.png",
  },
  {
    id: "1",
    name: "Asklepios Hospital Göttingen",
    address: "Rosdorfer Weg 70, 37081 Göttingen",
    stadt: "Göttingen",
    Google: 2.1,
    Klinikum: 1.4,
    rating_klinify: 1,
    image:
      "https://upload.wikimedia.org/wikipedia/commons/4/49/Asklepios_Fachklinikum_G%C3%B6ttingen_%281%29.JPG",
  },
  {
    id: "2",
    name: "Asklepios Hospital Tiefenbrunn",
    address: "Tiefenbrunn, 37124 Rosdorf",
    stadt: "Rosdorf",
    Google: 2.6,
    Klinikum: 2.6,
    rating_klinify: 2,
    image:
      "https://www.deutsches-krankenhaus-verzeichnis.de/app/file/image/show/ea64d9b452af986d_03e784fd-db0c-4ddf-b854-ff6cf6fbf326.png",
  },
  {
    id: "3",
    name: "Augenklinik Dr. Hoffmann",
    address: "Wolfenbütteler Str. 82, 38102 Braunschweig",
    stadt: "Braunschweig",
    Google: 4.0,
    Klinikum: 3.6,
    rating_klinify: 4,
    image:
      "https://www.deutsches-krankenhaus-verzeichnis.de/app/file/image/show/039d2d2d7948ef77_d08ce7f2-cdce-449d-a8fb-f11ed90eb888.png",
  },
  {
    id: "4",
    name: "DIAKOVERE Annastift",
    address: "Anna-von-Borries-Straße 1-7, 30625 Hannover",
    stadt: "Hannover",
    Google: 3.6,
    Klinikum: 3.7,
    rating_klinify: 4,
    image:
      "https://img.fotocommunity.com/annastift-i-hannover-9d4296bf-246d-4e54-ba00-12cc31f8294e.jpg?width=1000",
  },
  {
    id: "5",
    name: "DIAKOVERE Friederikenstift",
    address: "Humboldtstraße 5, 30169 Hannover",
    stadt: "Hannover",
    Google: 2.4,
    Klinikum: 2.5,
    rating_klinify: 2,
    image:
      "https://upload.wikimedia.org/wikipedia/commons/c/c6/Friederikenstift_Hannover.jpg",
  },
  {
    id: "6",
    name: "DRK-Krankenhaus Clementinenhaus",
    address: "Lützerodestraße 1, 30161 Hannover",
    stadt: "Hannover",
    Google: 4.0,
    Klinikum: 3.7,
    rating_klinify: 3,
    image:
      "https://www.clementinenhaus.de/wp-content/uploads/2020/12/Eingang-Clementinenhaus-1024x608.jpg",
  },
  {
    id: "7",
    name: "Helios Klinikum Hildesheim",
    address: "Senator-Braun-Allee 33, 31135 Hildesheim",
    stadt: "Hildesheim",
    Google: 2.2,
    Klinikum: 2.8,
    rating_klinify: 2,
    image:
      "https://www.helios-gesundheit.de/fileadmin/_processed_/5/1/csm_HI_Klinikum_IMG_0612_c1d37125d9.jpg",
  },
  {
    id: "8",
    name: "Herzogin Elisabeth Hospital",
    address: "Leipziger Str. 24, 38124 Braunschweig",
    stadt: "Braunschweig",
    Google: 4.1,
    Klinikum: 3.9,
    rating_klinify: 4,
    image:
      "https://cdn.regionalheute.de/images/2020/1/164/1000/911d87ffacaa43af8af14585e8584631.jpg",
  },
  {
    id: "9",
    name: "KRH Klinikum Großburgwedel",
    address: "Fuhrberger Str. 8, 30938 Burgwedel",
    stadt: "Burgwedel",
    Google: 2.5,
    Klinikum: 3.0,
    rating_klinify: 2,
    image:
      "https://www.hannover.de/var/storage/images/_aliases/alias_300x225px/media/01-data-neu/bilder/bilder-region-hannover/geb%C3%A4ude-der-region/klinikum-der-region-hannover/krh_klinikum_grossburgwedel/10578457-1-ger-DE/KRH_Klinikum_Grossburgwedel.jpg",
  },
  {
    id: "10",
    name: "KRH Klinikum Lehrte",
    address: "Manskestraße 22, 31275 Lehrte",
    stadt: "Lehrte",
    Google: 3.0,
    Klinikum: 2.7,
    rating_klinify: 2,
    image:
      "https://lehrte.krh.de/fileadmin/_processed_/5/2/csm_lehrte_787x300_763a970c44.jpg",
  },
  {
    id: "11",
    name: "Krankenhaus Lindenbrunn",
    address: "Am Lindenbrunn 1, 31863 Coppenbrügge",
    stadt: "Coppenbrügge",
    Google: 1.9,
    Klinikum: 3.7,
    rating_klinify: 2,
    image: "https://www.krankenhaus-lindenbrunn.de/_images/1062.jpg",
  },
  {
    id: "12",
    name: "Krankenhaus Marienstift gGmbH",
    address: "Helmstedter Str. 35, 38102 Braunschweig",
    stadt: "Braunschweig",
    Google: 3.6,
    Klinikum: 4.0,
    rating_klinify: 4,
    image:
      "https://www.neuerkerode.de/fileadmin/_processed_/c/f/csm_DC42536_b9d7705da0.jpg",
  },
  {
    id: "13",
    name: "Sana Klinikum Hameln-Pyrmont",
    address: "Saint-Maur-Platz 1, 31785 Hameln",
    stadt: "Hameln",
    Google: 2.1,
    Klinikum: 3.0,
    rating_klinify: 3,
    image:
      "https://www.sana.de/media/_processed_/0/5/csm_hameln_04b27514d6.jpg",
  },
  {
    id: "14",
    name: "Sophienklinik GmbH",
    address: "Bischofsholer Damm 160, 30173 Hannover",
    stadt: "Hannover",
    Google: 3.5,
    Klinikum: 3.0,
    rating_klinify: 4,
    image:
      "https://www.sophienklinik.de/wp-content/uploads/2018/05/sk_header_kontakt_neu.jpg",
  },
];
